### ISSUE TITLE
java.lang.NoSuchMethodError after upgrading to 1.1.7.4

### ISSUE THREAD

**Issue by cmuchinsky** [xerial/snappy-java#247]
Seeing the following after upgrading from 1.1.7.3 o 1.1.7.4:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:549)
```

**Comment by JimNero009** [comment]
I had the same issue -- decided to consolidate on this issue: #245

**Comment by xerial** [comment]
Just released 1.1.7.5, which is compiled by using jdk8. It looks like JDK9's ByteBuffer interface's compatibility issue.

**Comment by cmuchinsky** [comment]
Resolved with 1.1.7.5

**Comment by xerial** [comment]
@cmuchinsky Thank you for the confirmation!
