### ISSUE TITLE
Issue with musl after upgrading to v1.1.10.8

### ISSUE THREAD

**Issue by lucassaldanha** [xerial/snappy-java#692]
After updating our project to use snappy-java v1.1.10.8, some of our users reported an issue when starting the process:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
	at tech.pegasys.teku.networking.eth2.gossip.encoding.SnappyBlockCompressor.compress(SnappyBlockCompressor.java:54) ~[teku-networking-eth2-25.9.0.jar:25.9.0]
	at tech.pegasys.teku.networking.eth2.gossip.encoding.SszSnappyEncoding.encode(SszSnappyEncoding.java:38) ~[teku-networking-eth2-25.9.0.jar:25.9.0]
	at tech.pegasys.teku.networking.eth2.gossip.subnets.AttestationSubnetSubscriptions.lambda$gossip$0(AttestationSubnetSubscriptions.java:90) ~[teku-networking-eth2-25.9.0.jar:25.9.0]
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	... 46 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-5a7a1634-b5ef-475e-89cd-db2863cbec50-libsnappyjava.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
```

After looking through v1.1.10.8 changelog, I noticed the following change: https://github.com/xerial/snappy-java/pull/632

This change introduced a new code path that checks for the existence of `/lib/ld-musl-x86_64.so.1` (https://github.com/xerial/snappy-java/blob/main/src/main/java/org/xerial/snappy/OSInfo.java#L238-L244). However, it looks like during runtime, `libsnappyjava.so` is trying to load `libc.musl-x86_64.so.1`, and it fails.

I am not sure of the reason for this mismatch. It feels unintentional but maybe I am just misinformed. Either way, we have found a few workarounds.

1. We can create a symlink `libc.musl-x86_64.so.1 -> /lib/ld-musl-x86_64.so.1`; or
2. We can just completely uninstall `musl`.

Workaround 1 seems a bit hacky so we won't be asking our users to do so. Workaround 2 isn't great either, because musl is a dependency of grafana, and most of our users run a grafana instance on their nodes as well to monitor our process.

We are going to downgrade snappy-java to v1.1.10.7 in the mean time, until we have more information on this issue.

**Comment by lucassaldanha** [comment]
Tagging @xerial and @samyuh (the author of the PR) in case they can help with some extra context.

**Comment by samyuh** [comment]
Hey @lucassaldanha 

Thanks for pointing this out! It looks like that the exception being caught here should be more general and not specific.

I tested snappy with different images, however the catch block was changed after my commits here:

https://github.com/xerial/snappy-java/pull/632/commits/c3723e5241bc364b5c7f584fdbdea8bfe0ed3129

I can open a MR in the next few days to catch all the exceptions so we don't have a problem with this anymore.

**Comment by oliverwi** [comment]
This bug is impacting us as users of the on-prem version of Confluence, because we have Grafana installed on the same VM, which is why we have /lib/ld-musl-x86_64.so.1 on a GNU Linux system.

Unfortunately, Atlassian refuses to downgrade snappy to the previous version. Therefore, on every new Confluence version I manually replace snappy 1.1.10.8 jar with 1.1.10.7.

For reference, here is the Atlassian bug: https://jira.atlassian.com/browse/CONFSERVER-100761

The issue is in `src/main/java/org/xerial/snappy/OSInfo.java`, specifically the `isX64Musl()` method:
```java
return new File("/lib/ld-musl-x86_64.so.1").exists();
```

This incorrectly assumes that the presence of `/lib/ld-musl-x86_64.so.1` means the system is running musl.  However, this file can exist on glibc systems when packages like Grafana install musl as a dependency, when the system itself runs on glibc.

#### Proposed Solution

Check `/proc/self/map_files` for dynamically loaded libraries containing `ld-musl`. This detects what the JVM is actually using rather than what's installed on the system.

I'm working on a PR with this fix and will have it ready soon.

**Comment by XenoAmess** [comment]
> This bug is impacting us as users of the on-prem version of Confluence, because we have Grafana installed on the same VM, which is why we have /lib/ld-musl-x86_64.so.1 on a GNU Linux system.
> 
> Unfortunately, Atlassian refuses to downgrade snappy to the previous version. Therefore, on every new Confluence version I manually replace snappy 1.1.10.8 jar with 1.1.10.7.
> 
> For reference, here is the Atlassian bug: https://jira.atlassian.com/browse/CONFSERVER-100761
> 
> The issue is in `src/main/java/org/xerial/snappy/OSInfo.java`, specifically the `isX64Musl()` method:
> 
> return new File("/lib/ld-musl-x86_64.so.1").exists();
> This incorrectly assumes that the presence of `/lib/ld-musl-x86_64.so.1` means the system is running musl. However, this file can exist on glibc systems when packages like Grafana install musl as a dependency, when the system itself runs on glibc.
> 
> #### Proposed Solution
> Check `/proc/self/map_files` for dynamically loaded libraries containing `ld-musl`. This detects what the JVM is actually using rather than what's installed on the system.
> 
> I'm working on a PR with this fix and will have it ready soon.

be there any news?

**Comment by srstsavage** [comment]
@oliverwi Do you still have plans to submit a PR examining `/proc/self/map_files` to detect musl?

I'm wondering if just removing the attempted musl autodetection and requiring specification of the library path on musl systems would be the best path forward, as was done here:

https://github.com/dmlc/xgboost/pull/7921

In any case, this bug has been open for almost a year and a pragmatic immediate solution is probably better than a perfect future solution.

**Comment by XenoAmess** [comment]
> [@oliverwi](https://github.com/oliverwi) Do you still have plans to submit a PR examining `/proc/self/map_files` to detect musl?
> 
> I'm wondering if just removing the attempted musl autodetection and requiring specification of the library path on musl systems would be the best path forward, as was done here:
> 
> [dmlc/xgboost#7921](https://github.com/dmlc/xgboost/pull/7921)
> 
> In any case, this bug has been open for almost a year and a pragmatic immediate solution is probably better than a perfect future solution.

good point... why not implement it this way? shall I provide a pr? @oliverwi @xerial  @samyuh
